// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebsiteHuongNghiep.Data.EF;

namespace WebsiteHuongNghiep.Data.Migrations
{
    [DbContext(typeof(VocationalGuidanceDbContext))]
    [Migration("20211005103620_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebsiteHuongNghiep.Data.Entities.HollandMultipleChoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HLTableId")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("HLTableId");

                    b.ToTable("HollandMultipleChoices");
                });

            modelBuilder.Entity("WebsiteHuongNghiep.Data.Entities.HollandResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Result")
                        .HasColumnType("ntext");

                    b.Property<int>("Table")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HollandResult");
                });

            modelBuilder.Entity("WebsiteHuongNghiep.Data.Entities.HollandScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("Table")
                        .HasColumnType("int");

                    b.Property<string>("TimeStamp")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("HollandScore");
                });

            modelBuilder.Entity("WebsiteHuongNghiep.Data.Entities.HollandTable", b =>
                {
                    b.Property<int>("HLTableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("HLTableId");

                    b.ToTable("HollandTables");
                });

            modelBuilder.Entity("WebsiteHuongNghiep.Data.Entities.HollandTracker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Step")
                        .HasColumnType("int");

                    b.Property<string>("TimeStamp")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Times")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HollandTrackers");
                });

            modelBuilder.Entity("WebsiteHuongNghiep.Data.Entities.HollandMultipleChoice", b =>
                {
                    b.HasOne("WebsiteHuongNghiep.Data.Entities.HollandTable", "HollandTable")
                        .WithMany("HollandMutipleChoices")
                        .HasForeignKey("HLTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HollandTable");
                });

            modelBuilder.Entity("WebsiteHuongNghiep.Data.Entities.HollandTable", b =>
                {
                    b.Navigation("HollandMutipleChoices");
                });
#pragma warning restore 612, 618
        }
    }
}
